/*
Number Guessing Game
The following program randomly generates an integer greater than or equal to 0 and
less than 100. The program then prompts the user to guess the number. If the user
guesses the number correctly, the program outputs an appropriate message. Otherwise,
the program checks whether the guessed number is less than the random number. If
the guessed number is less than the random number generated by the program, the
program outputs the message "Your guess is lower than the number. Guess again!";
otherwise, the program outputs the message "Your guess is higher than the number.
Guess again!". The program then prompts the user to enter another number. The user
is prompted to guess the random number until the user enters the correct number.
*/
//Flag-controlled while loop.
//Number guessing game.
#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;
int main() 
{ 
    //declare the variables
    int num;
    int guess;
    //guessed by the user
    bool isGuessed; //boolean variable to control
    srand(time(0));
    num = rand() % 100;
    isGuessed = false;
    while (!isGuessed)
    {
        cout << "Enter an integer greater"
        << " than or equal to 0 and "
        << "less than 100: ";
        cin >> guess;
        cout << endl;
        if (guess == num)
        {
            cout << "You guessed the correct "
            << "number." << endl;
            isGuessed = true;
        }
        else if (guess < num)
            cout << "Your guess is lower than the " << "number.\n Guess again!" << endl;
        else
            cout << "Your guess is higher than " << "the number.\n Guess again!" << endl;
    } //end while
    return 0;
} 
