# Makefile for Writing Make Files Example
 
# *****************************************************
# Variables to control Makefile operation
# ****************************************************
 
CC = g++
CFLAGS = -Wall -g
 
# ****************************************************
# Targets needed to bring the executable up to date
# ****************************************************

####Q1
Q1: Q1.o  
	$(CC) $(CFLAGS) -o Q1 Q1.o  

Q1.o: Q1.cc 
	$(CC) $(CFLAGS) -c Q1.cc
	
### Q2
Q2: Q2.o  
	$(CC) $(CFLAGS) -o Q2 Q2.o  

Q2.o: Q2.cc 
	$(CC) $(CFLAGS) -c Q2.cc

###Q3
Q3: Q3.o  
	$(CC) $(CFLAGS) -o Q3 Q3.o  

Q3.o: Q3.cc 
	$(CC) $(CFLAGS) -c Q3.cc
